// =============================================================================
// GREENVILLE NC WEEKEND EVENTS DATA
// Weekend: February 27 (Friday) - March 1 (Sunday), 2026
// Radius: 2-hour drive from Greenville, NC 27858
// Design: Modern Trail Guide
// =============================================================================

export type BudgetTier = 'Free' | '$' | '$$' | '$$$' | '$$$$';
export type DayFilter = 'Friday' | 'Saturday' | 'Sunday';
export type TimeSlot = 'Morning' | 'Afternoon' | 'Evening' | 'All Day';
export type IndoorOutdoor = 'Indoor' | 'Outdoor' | 'Both';
export type Category =
  | 'Music'
  | 'Theater'
  | 'Sports'
  | 'Nature'
  | 'Arts & Culture'
  | 'Food & Drink'
  | 'History'
  | 'Family'
  | 'Brewery'
  | 'Festival'
  | 'Film'
  | 'Comedy'
  | 'Classes';

export interface Event {
  id: string;
  name: string;
  address: string;
  city: string;
  state: string;
  lat?: number;
  lng?: number;
  distanceMiles: number;
  driveTimeMinutes: number;
  days: DayFilter[];
  startTime: string; // "7:30 PM"
  endTime?: string;
  timeSlot: TimeSlot;
  price: string; // "$15", "Free", "$30-$68"
  budgetTier: BudgetTier;
  weather: string; // "Partly Cloudy 57°F"
  weatherIcon: string; // emoji
  indoorOutdoor: IndoorOutdoor;
  veganOptions: boolean | null; // null = unknown
  vegetarianOptions: boolean | null;
  category: Category;
  description: string;
  bookingUrl?: string;
  infoUrl?: string;
  imageQuery?: string; // for unsplash
  tags: string[];
}

// Weather for the weekend (Greenville NC area):
// Friday Feb 27: Partly cloudy, 50°F high / 48°F low, no rain
// Saturday Feb 28: Rain possible, 59°F high / 48°F low, 0.87in precip
// Sunday Mar 1: Clear, 69°F high / 44°F low, no rain

export const WEEKEND_WEATHER = {
  Friday: { condition: 'Partly Cloudy', high: 50, low: 48, icon: '⛅', rain: false },
  Saturday: { condition: 'Rain Possible', high: 59, low: 48, icon: '🌧️', rain: true },
  Sunday: { condition: 'Mostly Clear', high: 69, low: 44, icon: '🌤️', rain: false },
};

export const EVENTS: Event[] = [
  // ─── GREENVILLE (0 miles) ───────────────────────────────────────────────────
  {
    id: 'ecu-baseball-fri',
    name: 'Keith LeClair Classic – Day 1 (ECU vs Rutgers)',
    address: 'Lewis Field at Clark-LeClair Stadium, 9999 Charles Blvd',
    city: 'Greenville',
    state: 'NC',
    lat: 35.6127,
    lng: -77.3664,
    distanceMiles: 0,
    driveTimeMinutes: 0,
    days: ['Friday'],
    startTime: '4:30 PM',
    timeSlot: 'Afternoon',
    price: '$8–$15',
    budgetTier: '$',
    weather: 'Partly Cloudy 50°F',
    weatherIcon: '⛅',
    indoorOutdoor: 'Outdoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Sports',
    description: 'The 23rd annual Keith LeClair Classic collegiate baseball tournament hosted by East Carolina University. Day 1 features ECU Pirates vs. Rutgers Scarlet Knights at Lewis Field. A beloved tradition for ECU fans and baseball lovers alike.',
    bookingUrl: 'https://ecupirates.evenue.net/cgi-bin/ncommerce3/SEGetGroupList?groupCode=B&linkID=ecu',
    infoUrl: 'https://ecupirates.com/sports/baseball/schedule',
    tags: ['college baseball', 'ECU', 'outdoor', 'family-friendly'],
  },
  {
    id: 'ecu-baseball-sat',
    name: 'Keith LeClair Classic – Day 2 (ECU vs Troy)',
    address: 'Lewis Field at Clark-LeClair Stadium, 9999 Charles Blvd',
    city: 'Greenville',
    state: 'NC',
    lat: 35.6127,
    lng: -77.3664,
    distanceMiles: 0,
    driveTimeMinutes: 0,
    days: ['Saturday'],
    startTime: '4:30 PM',
    timeSlot: 'Afternoon',
    price: '$8–$15',
    budgetTier: '$',
    weather: 'Rain Possible 59°F',
    weatherIcon: '🌧️',
    indoorOutdoor: 'Outdoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Sports',
    description: 'Day 2 of the Keith LeClair Classic features ECU Pirates vs. Troy Trojans. Check weather forecast — bring a rain jacket just in case. The Jungle grass berm provides general admission seating.',
    bookingUrl: 'https://ecupirates.evenue.net/cgi-bin/ncommerce3/SEGetGroupList?groupCode=B&linkID=ecu',
    infoUrl: 'https://ecupirates.com/sports/baseball/schedule',
    tags: ['college baseball', 'ECU', 'outdoor'],
  },
  {
    id: 'ecu-baseball-sun',
    name: 'Keith LeClair Classic – Day 3 (ECU vs Western Carolina)',
    address: 'Lewis Field at Clark-LeClair Stadium, 9999 Charles Blvd',
    city: 'Greenville',
    state: 'NC',
    lat: 35.6127,
    lng: -77.3664,
    distanceMiles: 0,
    driveTimeMinutes: 0,
    days: ['Sunday'],
    startTime: '3:30 PM',
    timeSlot: 'Afternoon',
    price: '$8–$15',
    budgetTier: '$',
    weather: 'Mostly Clear 69°F',
    weatherIcon: '🌤️',
    indoorOutdoor: 'Outdoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Sports',
    description: 'Final day of the Keith LeClair Classic — ECU Pirates vs. Western Carolina Catamounts. Sunday ticket also includes the Troy vs. Rutgers game at 11 AM. Great weather expected for an afternoon at the ballpark.',
    bookingUrl: 'https://ecupirates.evenue.net/event/BB26/C08',
    infoUrl: 'https://ecupirates.com/sports/baseball/schedule',
    tags: ['college baseball', 'ECU', 'outdoor', 'double-header'],
  },
  {
    id: 'undaunted-escape',
    name: 'Undaunted Escape Rooms',
    address: '2800 East 10th St, Suite 103',
    city: 'Greenville',
    state: 'NC',
    lat: 35.6076,
    lng: -77.3498,
    distanceMiles: 0,
    driveTimeMinutes: 0,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: 'Various',
    endTime: 'Various',
    timeSlot: 'All Day',
    price: '$33–$40/person',
    budgetTier: '$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Family',
    description: 'Immersive escape room experiences with multiple themed rooms. Fri 4–11 PM, Sat 11:30 AM–11 PM, Sun 12:30–8 PM. Pricing based on group size with student discounts available. Perfect rainy-day activity.',
    bookingUrl: 'https://undauntedescaperooms.com/',
    infoUrl: 'https://undauntedescaperooms.com/',
    tags: ['escape room', 'indoor', 'groups', 'rainy day'],
  },
  {
    id: 'bowlero',
    name: 'Bowlero East Carolina',
    address: '700 Red Banks Rd',
    city: 'Greenville',
    state: 'NC',
    lat: 35.6021,
    lng: -77.3756,
    distanceMiles: 0,
    driveTimeMinutes: 0,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: 'Various',
    timeSlot: 'All Day',
    price: '$17.99+',
    budgetTier: '$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Family',
    description: 'Modern bowling alley with 40 lanes, arcade games, and a full sports bar. Night Strike specials on Fri/Sat evenings. Fri 3 PM–1 AM, Sat 11 AM–1 AM, Sun 12–11 PM. Great for groups and families.',
    bookingUrl: 'https://www.bowlero.com/location/bowlero-east-carolina',
    infoUrl: 'https://www.bowlero.com/location/bowlero-east-carolina',
    tags: ['bowling', 'indoor', 'family', 'arcade', 'bar'],
  },
  {
    id: 'captain-jacks',
    name: "Captain Jack's Indoor Mini Golf",
    address: '2903 E 10th St',
    city: 'Greenville',
    state: 'NC',
    lat: 35.6076,
    lng: -77.3476,
    distanceMiles: 0,
    driveTimeMinutes: 0,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: 'Various',
    timeSlot: 'All Day',
    price: '$8/person',
    budgetTier: '$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Family',
    description: 'Pirate-themed 18-hole indoor mini golf with free popcorn with every game. Snack bar on site. Fri 12 PM–12 AM, Sat 11 AM–12 AM, Sun 11 AM–8 PM. Budget-friendly fun for all ages.',
    bookingUrl: 'https://captainjacksminigolf.com/',
    infoUrl: 'https://captainjacksminigolf.com/',
    tags: ['mini golf', 'indoor', 'family', 'kids', 'budget-friendly'],
  },
  {
    id: 'art-ball-2026',
    name: 'Art Ball 2026 – Greenville Museum of Art',
    address: 'Hilton Greenville, 207 SW Greenville Blvd',
    city: 'Greenville',
    state: 'NC',
    lat: 35.6127,
    lng: -77.3943,
    distanceMiles: 0,
    driveTimeMinutes: 0,
    days: ['Saturday'],
    startTime: '6:00 PM',
    endTime: '10:00 PM',
    timeSlot: 'Evening',
    price: '$135–$185/person',
    budgetTier: '$$$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Arts & Culture',
    description: "The Greenville Museum of Art's premier annual fundraiser. Features fine dining, open bar, silent and live auctions, and art exhibitions. Supports GMoA's exhibitions, education, and community programs. Members $135, non-members $185.",
    bookingUrl: 'https://www.gmoa.org/art-ball',
    infoUrl: 'https://www.gmoa.org/events-details/art-ball-2026',
    tags: ['gala', 'art', 'fundraiser', 'formal', 'upscale'],
  },

  // ─── WASHINGTON NC (31 mi / 45 min) ─────────────────────────────────────────
  {
    id: 'goose-creek-sp',
    name: 'Goose Creek State Park',
    address: '2190 Camp Leach Road',
    city: 'Washington',
    state: 'NC',
    lat: 35.4921,
    lng: -76.9254,
    distanceMiles: 31,
    driveTimeMinutes: 45,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: '8:00 AM',
    endTime: '8:00 PM',
    timeSlot: 'All Day',
    price: 'Free',
    budgetTier: 'Free',
    weather: 'Outdoor – check forecast',
    weatherIcon: '🌳',
    indoorOutdoor: 'Outdoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Nature',
    description: 'Coastal state park offering wetlands along the Pamlico River, cypress swamp, hiking trails, paddling, fishing, and picnicking. 8 AM–6 PM Friday, 8 AM–8 PM Sat–Sun. Stunning late-winter bird watching opportunities.',
    infoUrl: 'https://www.ncparks.gov/state-parks/goose-creek-state-park',
    tags: ['hiking', 'nature', 'free', 'paddling', 'fishing', 'birds'],
  },

  // ─── NEW BERN (46 mi / 60 min) ───────────────────────────────────────────────
  {
    id: 'tryon-palace',
    name: 'Tryon Palace Historic Site & Gardens',
    address: '529 S Front St',
    city: 'New Bern',
    state: 'NC',
    lat: 35.1054,
    lng: -77.0441,
    distanceMiles: 46,
    driveTimeMinutes: 60,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: '10:00 AM',
    endTime: '5:00 PM',
    timeSlot: 'All Day',
    price: '$10–$22',
    budgetTier: '$$',
    weather: 'Both – gardens outdoor',
    weatherIcon: '🏛️',
    indoorOutdoor: 'Both',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'History',
    description: "North Carolina's first permanent capitol and a living history experience. Tour the reconstructed 1770 Palace, historic homes, and 14 acres of formal gardens. The NC History Center features interactive exhibits. Mon–Sat 10 AM–5 PM, Sun 12–5 PM.",
    bookingUrl: 'https://www.tryonpalace.org/plan-your-visit/tickets',
    infoUrl: 'https://www.tryonpalace.org/',
    tags: ['history', 'colonial', 'gardens', 'museum', 'family'],
  },

  // ─── CLIFFS OF NEUSE (49 mi / 64 min) ────────────────────────────────────────
  {
    id: 'cliffs-neuse',
    name: 'Cliffs of the Neuse State Park – Ranger Hike',
    address: '240 Park Entrance Road',
    city: 'Seven Springs',
    state: 'NC',
    lat: 35.2143,
    lng: -77.8765,
    distanceMiles: 49,
    driveTimeMinutes: 64,
    days: ['Friday', 'Saturday'],
    startTime: 'Fri 2:00 PM / Sat 7:00 PM',
    timeSlot: 'Afternoon',
    price: 'Free (day use)',
    budgetTier: 'Free',
    weather: 'Outdoor – check forecast',
    weatherIcon: '🌳',
    indoorOutdoor: 'Outdoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Nature',
    description: 'Spectacular 90-foot bluffs overlooking the Neuse River. Friday: Hike with a Ranger 2–3 PM. Saturday: Special Moonlight Hike with a Ranger 7–8 PM. Park open 7 AM–6 PM Fri, 7 AM–8 PM Sat–Sun. Free day use; boat rental fees apply.',
    infoUrl: 'https://www.ncparks.gov/state-parks/cliffs-neuse-state-park',
    tags: ['hiking', 'ranger hike', 'moonlight', 'nature', 'free', 'scenic'],
  },

  // ─── FOUR OAKS (68 mi / 70 min) ──────────────────────────────────────────────
  {
    id: 'bentonville-battlefield',
    name: 'Bentonville Battlefield State Historic Site',
    address: '5466 Harper House Rd',
    city: 'Four Oaks',
    state: 'NC',
    lat: 35.3254,
    lng: -78.3265,
    distanceMiles: 68,
    driveTimeMinutes: 70,
    days: ['Saturday'],
    startTime: '9:00 AM',
    endTime: '5:00 PM',
    timeSlot: 'All Day',
    price: 'Free',
    budgetTier: 'Free',
    weather: 'Both',
    weatherIcon: '🏛️',
    indoorOutdoor: 'Both',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'History',
    description: "The largest Civil War battlefield in North Carolina, site of the last major Confederate offensive. Features a visitor center, the Harper House (used as a field hospital), and self-guided battlefield trails. Open Tue–Sat 9 AM–5 PM.",
    infoUrl: 'https://historicsites.nc.gov/all-sites/bentonville-battlefield',
    tags: ['civil war', 'history', 'battlefield', 'free', 'museum'],
  },

  // ─── SMITHFIELD (66 mi / 67 min) ─────────────────────────────────────────────
  {
    id: 'raleigh-brewing-karaoke',
    name: 'Cocktails & Karaoke at Raleigh Brewing JoCo',
    address: '3174 US-70',
    city: 'Smithfield',
    state: 'NC',
    lat: 35.5087,
    lng: -78.3376,
    distanceMiles: 66,
    driveTimeMinutes: 67,
    days: ['Friday'],
    startTime: '7:00 PM',
    endTime: '10:00 PM',
    timeSlot: 'Evening',
    price: '$3 drinks (no cover)',
    budgetTier: '$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: true,
    vegetarianOptions: true,
    category: 'Brewery',
    description: 'Karaoke night at Raleigh Brewing JoCo hosted by DJ Shannon NC. $3 well drinks and $3 select appetizers. Craft beers on tap. Menu includes Veggie Quesadilla and Veggie Caesar Wrap. Fun neighborhood brewery atmosphere.',
    bookingUrl: 'https://www.raleighbrewing.com/event-details/cocktails-karaoke-at-raleigh-brewing-joco-2026-02-27-19-00',
    infoUrl: 'https://www.raleighbrewing.com/',
    tags: ['karaoke', 'brewery', 'craft beer', 'vegetarian', 'vegan', 'nightlife'],
  },

  // ─── CRESWELL (71 mi / 89 min) ───────────────────────────────────────────────
  {
    id: 'pettigrew-sp',
    name: 'Pettigrew State Park & Lake Phelps',
    address: '2252 Lake Shore Road',
    city: 'Creswell',
    state: 'NC',
    lat: 35.8021,
    lng: -76.3987,
    distanceMiles: 71,
    driveTimeMinutes: 89,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: '8:00 AM',
    endTime: '8:00 PM',
    timeSlot: 'All Day',
    price: 'Free',
    budgetTier: 'Free',
    weather: 'Outdoor – check forecast',
    weatherIcon: '🌳',
    indoorOutdoor: 'Outdoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Nature',
    description: 'Pristine blackwater lake surrounded by ancient cypress trees. Pettigrew State Park showcases the rich habitat of Lake Phelps and the Scuppernong River. Hiking, biking, paddling, fishing, and picnicking. One of NC\'s most serene natural areas.',
    infoUrl: 'https://www.ncparks.gov/state-parks/pettigrew-state-park',
    tags: ['lake', 'hiking', 'paddling', 'fishing', 'free', 'nature', 'scenic'],
  },

  // ─── RALEIGH (85 mi / 81 min) ────────────────────────────────────────────────
  {
    id: 'peter-rowan',
    name: 'Peter Rowan – Down Home Concert Series',
    address: 'A.J. Fletcher Opera Theater, 2 E South St',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.7796,
    lng: -78.6382,
    distanceMiles: 85,
    driveTimeMinutes: 81,
    days: ['Friday'],
    startTime: '7:30 PM',
    timeSlot: 'Evening',
    price: '$34–$65',
    budgetTier: '$$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Music',
    description: "Grammy-winning bluegrass legend Peter Rowan performs at the Martin Marietta Center. A 2022 inductee into the International Bluegrass Music Hall of Fame, Rowan has spent over five decades shaping American roots music. An intimate evening of masterful storytelling.",
    bookingUrl: 'https://www.martinmariettacenter.com/events/detail/peter-rowan',
    infoUrl: 'https://www.visitraleigh.com/event/2026-down-home-concert-series%3a-peter-rowan/101841/',
    tags: ['bluegrass', 'folk', 'roots music', 'concert', 'Grammy winner'],
  },
  {
    id: 'arkona-concert',
    name: 'ARKONA / Malphas – Metal Concert',
    address: 'Chapel of Bones, 658 Maywood Ave Ste B110',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.7654,
    lng: -78.6543,
    distanceMiles: 85,
    driveTimeMinutes: 81,
    days: ['Friday'],
    startTime: '7:00 PM',
    timeSlot: 'Evening',
    price: '$25.50–$32',
    budgetTier: '$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Music',
    description: 'Legendary Russian pagan folk metal band Arkona brings their powerful live ritual to Raleigh. Fronted by the commanding Masha Scream, the band blends crushing extreme metal with traditional folk instrumentation. An epic, immersive live experience.',
    bookingUrl: 'https://www.tickpick.com/organizer/event/arkona-malphas-nox-eternus-25960129',
    infoUrl: 'https://www.visitraleigh.com/event/arkona-malphas/103562/',
    tags: ['metal', 'folk metal', 'pagan', 'concert', 'nightlife'],
  },
  {
    id: 'candlelight-coldplay',
    name: 'Candlelight: Coldplay & Imagine Dragons',
    address: 'The Rialto, 1620 Glenwood Avenue',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.8012,
    lng: -78.6621,
    distanceMiles: 85,
    driveTimeMinutes: 81,
    days: ['Friday'],
    startTime: '8:45 PM',
    endTime: '10:00 PM',
    timeSlot: 'Evening',
    price: '$35+',
    budgetTier: '$$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Music',
    description: 'Experience the magic of Coldplay & Imagine Dragons performed live under the gentle glow of hundreds of candles at The Rialto. A multi-sensory musical experience in a stunning venue. Romantic and unforgettable.',
    bookingUrl: 'https://feverup.com/m/250852',
    infoUrl: 'https://www.visitraleigh.com/event/candlelight%3a-coldplay-%26-imagine-dragons/103326/',
    tags: ['candlelight', 'pop', 'romantic', 'concert', 'unique experience'],
  },
  {
    id: 'aacc-raleigh',
    name: '25th Annual African American Cultural Celebration',
    address: 'NC Museum of Art, 2110 Blue Ridge Rd',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.8021,
    lng: -78.6876,
    distanceMiles: 85,
    driveTimeMinutes: 81,
    days: ['Saturday'],
    startTime: '10:30 AM',
    endTime: '4:30 PM',
    timeSlot: 'Morning',
    price: 'Free',
    budgetTier: 'Free',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Festival',
    description: 'The 25th Annual African American Cultural Celebration at the NC Museum of Art celebrates Black History Month with live performances, demonstrations, art, food, and community. Free admission. A vibrant, family-friendly cultural festival.',
    bookingUrl: 'https://ncartmuseum.org/events/25th-annual-african-american-cultural-celebration/',
    infoUrl: 'https://www.ncmuseumofhistory.org/aacc',
    tags: ['cultural', 'free', 'Black History Month', 'family', 'art', 'music', 'food'],
  },
  {
    id: 'raleigh-brewing-live',
    name: 'RBC After Dark: Zac Lor Live at Raleigh Brewing',
    address: '3709 Neil St',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.7765,
    lng: -78.6754,
    distanceMiles: 85,
    driveTimeMinutes: 81,
    days: ['Saturday'],
    startTime: '9:00 PM',
    endTime: '12:00 AM',
    timeSlot: 'Evening',
    price: 'TBD (check website)',
    budgetTier: '$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: true,
    vegetarianOptions: true,
    category: 'Brewery',
    description: 'Live performance by Zac Lor at Raleigh Brewing\'s Neil Street taproom. When the lights go low, the beats turn up! Craft beers on tap, full food menu with vegetarian and vegan options including Veggie Quesadilla.',
    bookingUrl: 'https://www.raleighbrewing.com/upcoming-events',
    infoUrl: 'https://www.raleighbrewing.com/',
    tags: ['live music', 'brewery', 'craft beer', 'nightlife', 'vegetarian', 'vegan'],
  },
  {
    id: 'taste-of-ireland-raleigh',
    name: 'A Taste of Ireland – Irish Music & Dance',
    address: 'A.J. Fletcher Opera Theater, 2 E South St',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.7796,
    lng: -78.6382,
    distanceMiles: 85,
    driveTimeMinutes: 81,
    days: ['Sunday'],
    startTime: '3:00 PM',
    timeSlot: 'Afternoon',
    price: 'TBD (check website)',
    budgetTier: '$$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Theater',
    description: 'After premiering Off-Broadway, A Taste of Ireland returns with Celtic music, traditional dance, and storytelling. Laugh, cry and jig into the night with a production that has entertained thousands around the globe.',
    bookingUrl: 'https://www.martinmariettacenter.com/events/detail/a-taste-of-ireland-g5evzbyxtwsob',
    infoUrl: 'https://www.martinmariettacenter.com/',
    tags: ['Irish', 'dance', 'Celtic', 'theater', 'St. Patricks'],
  },
  {
    id: 'raleigh-brewing-shakespeare',
    name: 'Elsewhere Shakespeare: As You Like It at Raleigh Brewing',
    address: '3709 Neil St',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.7765,
    lng: -78.6754,
    distanceMiles: 85,
    driveTimeMinutes: 81,
    days: ['Sunday'],
    startTime: '5:00 PM',
    endTime: '6:30 PM',
    timeSlot: 'Afternoon',
    price: 'TBD (check website)',
    budgetTier: '$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: true,
    vegetarianOptions: true,
    category: 'Theater',
    description: '"All the world\'s a stage..." Enjoy Shakespeare\'s "As You Like It" performed by Elsewhere Shakespeare at Raleigh Brewing. A unique cultural experience pairing classic theater with craft beer. Vegetarian and vegan food options available.',
    bookingUrl: 'https://www.raleighbrewing.com/upcoming-events',
    infoUrl: 'https://www.raleighbrewing.com/',
    tags: ['Shakespeare', 'theater', 'brewery', 'unique', 'vegetarian', 'vegan'],
  },
  {
    id: 'pinots-palette-fri',
    name: "Pinot's Palette – Northern Lights Lake View Paint Class",
    address: '10410 Moncreiffe Road Suite 101',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.8654,
    lng: -78.5432,
    distanceMiles: 84,
    driveTimeMinutes: 81,
    days: ['Friday'],
    startTime: '7:00 PM',
    endTime: '9:30 PM',
    timeSlot: 'Evening',
    price: '$39',
    budgetTier: '$$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Classes',
    description: 'Guided painting class where you\'ll create a beautiful Northern Lights lake view scene. All materials provided. BYOB welcome. Perfect date night or girls\' night out activity. No experience needed.',
    bookingUrl: 'https://www.pinotspalette.com/briercreek',
    infoUrl: 'https://www.pinotspalette.com/briercreek',
    tags: ['painting', 'art class', 'date night', 'BYOB', 'creative'],
  },
  {
    id: 'pinots-palette-sat',
    name: "Pinot's Palette – Goldfinch and Thistles Paint Class",
    address: '10410 Moncreiffe Road Suite 101',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.8654,
    lng: -78.5432,
    distanceMiles: 84,
    driveTimeMinutes: 81,
    days: ['Saturday'],
    startTime: '3:00 PM',
    endTime: '5:00 PM',
    timeSlot: 'Afternoon',
    price: '$39',
    budgetTier: '$$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Classes',
    description: 'Paint a beautiful scene of goldfinches and thistles in this guided art class. All materials provided. BYOB welcome. Great rainy Saturday activity — and Saturday has rain in the forecast!',
    bookingUrl: 'https://www.pinotspalette.com/briercreek',
    infoUrl: 'https://www.pinotspalette.com/briercreek',
    tags: ['painting', 'art class', 'BYOB', 'creative', 'rainy day'],
  },
  {
    id: 'nc-natural-sciences',
    name: 'NC Museum of Natural Sciences',
    address: '11 West Jones Street',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.7815,
    lng: -78.6390,
    distanceMiles: 85,
    driveTimeMinutes: 81,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: '10:00 AM',
    endTime: '5:00 PM',
    timeSlot: 'All Day',
    price: 'Free (3D movies: donations)',
    budgetTier: 'Free',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Family',
    description: 'The largest natural history museum in the Southeast. Features live animals, 3D movies (Secrets of the Sea, T. Rex), daily ranger programs, and hands-on exhibits. Free admission. 3D movies shown multiple times daily with donations accepted.',
    bookingUrl: 'https://naturalsciences.org/visit/3d-movies',
    infoUrl: 'https://naturalsciences.org/',
    tags: ['museum', 'science', 'free', 'family', 'kids', '3D movies', 'animals'],
  },
  {
    id: 'pope-house-museum',
    name: 'Pope House Museum',
    address: '511 S Wilmington St',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.7732,
    lng: -78.6376,
    distanceMiles: 85,
    driveTimeMinutes: 81,
    days: ['Saturday'],
    startTime: '10:00 AM',
    endTime: '3:00 PM',
    timeSlot: 'Morning',
    price: 'Free',
    budgetTier: 'Free',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'History',
    description: 'Built in 1901, the Pope House Museum offers a glimpse into the life of Dr. Manassa Thomas Pope, one of the first African American graduates of the Leonard School of Medicine at Shaw University. Tours every hour, last tour at 2 PM. Saturdays only.',
    infoUrl: 'https://www.visitraleigh.com/plan-a-trip/visitraleigh-insider-blog/post/the-best-historic-sites-to-visit-in-raleigh-nc/',
    tags: ['history', 'African American history', 'free', 'museum', 'Black History Month'],
  },
  {
    id: 'mordecai-historic',
    name: 'Mordecai Historic Park',
    address: '1 Mimosa St',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.7943,
    lng: -78.6265,
    distanceMiles: 85,
    driveTimeMinutes: 81,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: '10:00 AM',
    endTime: '4:00 PM',
    timeSlot: 'All Day',
    price: 'Free–$5',
    budgetTier: '$',
    weather: 'Both',
    weatherIcon: '🏛️',
    indoorOutdoor: 'Both',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'History',
    description: 'Once the largest plantation in Wake County. Tour the Mordecai House (built 1785) and birthplace of President Andrew Johnson. 19th-century kitchen garden. Guided tours hourly, last tour at 3 PM. Tue–Sat 10 AM–4 PM, Sun 1–4 PM.',
    infoUrl: 'https://www.visitraleigh.com/plan-a-trip/visitraleigh-insider-blog/post/the-best-historic-sites-to-visit-in-raleigh-nc/',
    tags: ['history', 'plantation', 'presidential', 'free', 'guided tour'],
  },
  {
    id: 'dixie-deer-classic',
    name: 'Dixie Deer Classic – Hunting & Outdoor Expo',
    address: 'NC State Fairgrounds, 4285 Trinity Road',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.7876,
    lng: -78.7321,
    distanceMiles: 85,
    driveTimeMinutes: 81,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: 'Fri 11AM / Sat 9AM / Sun 9AM',
    endTime: 'Fri 8PM / Sat 7PM / Sun 4PM',
    timeSlot: 'All Day',
    price: '$12 (1-day) / $20 (weekend)',
    budgetTier: '$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Festival',
    description: 'Premier whitetail deer, hunting, and outdoor expo with 350+ exhibitors, deer scoring, seminars, raffles, Venison Chili Cook-Off, Carolina Dock Dogs, and Kids Scavenger Hunt. Children 12 and under FREE.',
    bookingUrl: 'https://brushfire.com/dixiedeerclassic2026/dixie-deer-classic/611459',
    infoUrl: 'https://dixiedeerclassic.org/',
    tags: ['hunting', 'outdoor', 'expo', 'family', 'kids free'],
  },

  // ─── WAKE FOREST (90 mi / 85 min) ────────────────────────────────────────────
  {
    id: 'tannahill-weavers',
    name: 'An Evening with the Tannahill Weavers',
    address: 'Wake Forest Listening Room, 415 Brooks St',
    city: 'Wake Forest',
    state: 'NC',
    lat: 35.9765,
    lng: -78.5098,
    distanceMiles: 90,
    driveTimeMinutes: 85,
    days: ['Friday'],
    startTime: '7:30 PM',
    endTime: '10:00 PM',
    timeSlot: 'Evening',
    price: '$28.25',
    budgetTier: '$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Music',
    description: "Celebrate Scotland's rich musical heritage with the Tannahill Weavers, one of Scotland's premier traditional bands. Driving rhythms, powerful vocals, pipes, flute, fiddle, guitar, and bouzouki bring Celtic melodies to life. Doors 6:45 PM.",
    bookingUrl: 'https://www.etix.com/ticket/p/98681208/an-evening-with-the-tannahill-weavers-wake-forest-wake-forest-listening-room',
    infoUrl: 'https://www.visitraleigh.com/event/an-evening-with-the-tannahill-weavers/99921/',
    tags: ['Celtic', 'folk', 'Scottish', 'traditional', 'concert'],
  },

  // ─── NC AQUARIUM (90 mi / 90 min) ────────────────────────────────────────────
  {
    id: 'nc-aquarium-pks',
    name: 'NC Aquarium at Pine Knoll Shores',
    address: '1 Roosevelt Blvd',
    city: 'Pine Knoll Shores',
    state: 'NC',
    lat: 34.6987,
    lng: -76.8234,
    distanceMiles: 90,
    driveTimeMinutes: 90,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: '9:00 AM',
    endTime: '5:00 PM',
    timeSlot: 'All Day',
    price: '$15/adults, $13/kids',
    budgetTier: '$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Family',
    description: 'Journey from NC mountains to the Crystal Coast. Explore shipwrecks and see thousands of aquatic animals including sharks, sea turtles, and stingrays. Advance tickets recommended. Open daily 9 AM–5 PM. Near beautiful Crystal Coast beaches.',
    bookingUrl: 'https://www.ncaquariums.com/pine-knoll-shores',
    infoUrl: 'https://www.ncaquariums.com/pine-knoll-shores',
    tags: ['aquarium', 'family', 'kids', 'Crystal Coast', 'marine life'],
  },

  // ─── DURHAM (109 mi / 104 min) ───────────────────────────────────────────────
  {
    id: 'seth-meyers',
    name: 'Seth Meyers: Live Stand-Up Comedy',
    address: 'Durham Performing Arts Center, 123 Vivian St',
    city: 'Durham',
    state: 'NC',
    lat: 35.9940,
    lng: -78.8986,
    distanceMiles: 109,
    driveTimeMinutes: 104,
    days: ['Friday'],
    startTime: '7:00 PM',
    timeSlot: 'Evening',
    price: 'Check DPAC website',
    budgetTier: '$$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Comedy',
    description: 'Emmy Award-winning writer and host of NBC\'s "Late Night with Seth Meyers" brings his stand-up comedy tour to DPAC. Former SNL cast member and head writer. A rare chance to see one of late-night\'s biggest names live.',
    bookingUrl: 'https://www.dpacnc.com/events/detail/seth_meyers2026',
    infoUrl: 'https://www.dpacnc.com/events/detail/seth_meyers2026',
    tags: ['comedy', 'stand-up', 'SNL', 'late night', 'celebrity'],
  },
  {
    id: 'brett-young',
    name: 'Brett Young – Country Concert',
    address: 'Durham Performing Arts Center, 123 Vivian St',
    city: 'Durham',
    state: 'NC',
    lat: 35.9940,
    lng: -78.8986,
    distanceMiles: 109,
    driveTimeMinutes: 104,
    days: ['Sunday'],
    startTime: '8:00 PM',
    timeSlot: 'Evening',
    price: 'Check DPAC website',
    budgetTier: '$$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Music',
    description: 'Country star Brett Young brings his "Caliville" sound to DPAC. With 8.5 billion global streams and seven consecutive #1 singles, Rolling Stone calls him "one of Country\'s most consistent radio stars." Romantic country pop at its finest.',
    bookingUrl: 'https://www.dpacnc.com/events/detail/brett_young2026',
    infoUrl: 'https://www.dpacnc.com/events/detail/brett_young2026',
    tags: ['country', 'concert', 'DPAC', 'pop country', 'romance'],
  },
  {
    id: 'nevermore-film-fest',
    name: 'Nevermore Film Festival – Horror & Dark Fantasy',
    address: 'Carolina Theatre, 309 W Morgan St',
    city: 'Durham',
    state: 'NC',
    lat: 35.9965,
    lng: -78.9021,
    distanceMiles: 109,
    driveTimeMinutes: 104,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: 'Various showtimes',
    timeSlot: 'All Day',
    price: '$13.50/film or $60 (5-pass)',
    budgetTier: '$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Film',
    description: 'The 27th Annual Nevermore Film Festival showcases horror, dark fantasy, mystery, thriller, and sci-fi films from around the world. 8 feature films and 73 shorts, including 2 U.S. premieres and 9 world premieres from 14 countries. A beloved Triangle tradition.',
    bookingUrl: 'https://carolinatheatre.org/festival/nevermore-film-festival/',
    infoUrl: 'https://carolinatheatre.org/news/the-27th-annual-nevermore-film-festival-comes-to-the-carolina-theatre-february-27-march-1/',
    tags: ['film festival', 'horror', 'sci-fi', 'indie film', 'world premieres'],
  },
  {
    id: 'duke-basketball',
    name: 'Duke Men\'s Basketball vs. Virginia (ACC)',
    address: 'Cameron Indoor Stadium, 115 Whitford Dr',
    city: 'Durham',
    state: 'NC',
    lat: 36.0010,
    lng: -78.9413,
    distanceMiles: 109,
    driveTimeMinutes: 104,
    days: ['Saturday'],
    startTime: '12:00 PM',
    timeSlot: 'Morning',
    price: 'From $17 (resale)',
    budgetTier: '$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Sports',
    description: 'Duke Blue Devils face the Virginia Cavaliers in an ACC conference game at the legendary Cameron Indoor Stadium. One of the most electric atmospheres in college basketball. Resale tickets available from $17.',
    bookingUrl: 'https://seatgeek.com/duke-blue-devils-mens-basketball-tickets/ncaa-basketball/2026-02-28-12-pm/17724477',
    infoUrl: 'https://goduke.com/sports/mens-basketball/schedule',
    tags: ['college basketball', 'Duke', 'ACC', 'Cameron Indoor', 'sports'],
  },
  {
    id: 'bennett-place',
    name: 'Bennett Place State Historic Site',
    address: '4409 Bennett Memorial Rd',
    city: 'Durham',
    state: 'NC',
    lat: 36.0287,
    lng: -78.9654,
    distanceMiles: 109,
    driveTimeMinutes: 104,
    days: ['Saturday'],
    startTime: '9:00 AM',
    endTime: '5:00 PM',
    timeSlot: 'All Day',
    price: 'Free (tours $1–$4)',
    budgetTier: '$',
    weather: 'Both',
    weatherIcon: '🏛️',
    indoorOutdoor: 'Both',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'History',
    description: 'Site of the largest troop surrender of the Civil War. Reconstructed farmhouse, kitchen, and smokehouse recall ordinary Southern farm life during the Civil War. Guided tours at 11 AM, 1 PM, and 3 PM. Tue–Sat 9 AM–5 PM.',
    infoUrl: 'https://historicsites.nc.gov/all-sites/bennett-place',
    tags: ['civil war', 'history', 'battlefield', 'guided tour', 'free admission'],
  },

  // ─── CARRBORO (113 mi / 111 min) ─────────────────────────────────────────────
  {
    id: 'carrboro-film-fest',
    name: 'Carrboro Film Festival – 20th Annual',
    address: 'Drakeford Library Complex, 203 S Greensboro St',
    city: 'Carrboro',
    state: 'NC',
    lat: 35.9101,
    lng: -79.0754,
    distanceMiles: 113,
    driveTimeMinutes: 111,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: 'Various showtimes',
    timeSlot: 'All Day',
    price: '$8/film',
    budgetTier: '$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Film',
    description: 'The 20th Annual Carrboro Film Festival celebrates independent cinema at the new Drakeford Library Complex in downtown Carrboro. Bringing filmmakers and audiences together for a weekend of diverse independent films.',
    bookingUrl: 'https://www.visitchapelhill.org/events/annual-events/',
    infoUrl: 'https://www.visitchapelhill.org/events/annual-events/',
    tags: ['film festival', 'indie film', 'independent cinema', 'Carrboro'],
  },

  // ─── WILMINGTON (120 mi / 120 min) ───────────────────────────────────────────
  {
    id: 'wilmington-marathon',
    name: 'Novant Health Wilmington NC Marathon',
    address: 'Downtown Wilmington, Live Oak Bank Pavilion',
    city: 'Wilmington',
    state: 'NC',
    lat: 34.2257,
    lng: -77.9447,
    distanceMiles: 120,
    driveTimeMinutes: 120,
    days: ['Saturday'],
    startTime: '7:00 AM',
    timeSlot: 'Morning',
    price: '$120–$165 (registration)',
    budgetTier: '$$$',
    weather: 'Outdoor – check forecast',
    weatherIcon: '🌧️',
    indoorOutdoor: 'Outdoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Sports',
    description: 'The Novant Health Wilmington NC Marathon features a full marathon, half marathon, 5K, and 1-mile Glow Run. Half marathon starts at Johnny Mercer Pier in Wrightsville Beach and finishes downtown. Spectator-friendly event with great atmosphere.',
    bookingUrl: 'https://runsignup.com/Race/NC/Wilmington/WilmingtonMarathon',
    infoUrl: 'https://wilmingtonncmarathon.com/',
    tags: ['marathon', 'running', 'half marathon', '5K', 'spectator', 'fitness'],
  },
  {
    id: 'to-kill-mockingbird',
    name: "'To Kill a Mockingbird' – Thalian Hall",
    address: 'Thalian Hall, 310 Chestnut St',
    city: 'Wilmington',
    state: 'NC',
    lat: 34.2354,
    lng: -77.9476,
    distanceMiles: 120,
    driveTimeMinutes: 120,
    days: ['Friday', 'Saturday'],
    startTime: '7:30 PM',
    timeSlot: 'Evening',
    price: 'Check Thalian Hall website',
    budgetTier: '$$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Theater',
    description: "Former Wilmington actor Cullen Moss (Netflix's 'Outer Banks,' HBO Max's 'The Staircase') returns to star as Atticus Finch in Harper Lee's classic. A powerful theatrical production at the historic Thalian Hall. 7:30 PM Fri–Sat.",
    bookingUrl: 'https://www.thalianhall.org/',
    infoUrl: 'https://www.starnewsonline.com/story/entertainment/events/2026/02/25/events-happenings-things-to-do-whats-going-on-in-wilmington-nc-festivals-comedy-music-theater/88643157007/',
    tags: ['theater', 'classic', 'Harper Lee', 'Thalian Hall', 'drama'],
  },
  {
    id: 'come-from-away',
    name: "'Come From Away' Musical – North Front Theatre",
    address: 'North Front Theatre, Wilmington',
    city: 'Wilmington',
    state: 'NC',
    lat: 34.2354,
    lng: -77.9476,
    distanceMiles: 120,
    driveTimeMinutes: 120,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: 'Fri–Sat 7:30 PM / Sun 2:00 PM',
    timeSlot: 'Evening',
    price: 'Check website',
    budgetTier: '$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Theater',
    description: "And Seen Theatrical Productions presents this heartwarming musical about when thousands of airline passengers were forced to land in tiny Gander, Newfoundland, on 9/11. A touching story of community and kindness. 7:30 PM Fri–Sat, 2 PM Sat–Sun.",
    infoUrl: 'https://www.starnewsonline.com/story/entertainment/events/2026/02/25/events-happenings-things-to-do-whats-going-on-in-wilmington-nc-festivals-comedy-music-theater/88643157007/',
    tags: ['musical', 'theater', '9/11', 'heartwarming', 'community'],
  },
  {
    id: 'geoffrey-asmus-comedy',
    name: 'Geoffrey Asmus – Stand-Up Comedy',
    address: 'Dead Crow Comedy Room, Wilmington',
    city: 'Wilmington',
    state: 'NC',
    lat: 34.2354,
    lng: -77.9476,
    distanceMiles: 120,
    driveTimeMinutes: 120,
    days: ['Friday', 'Saturday'],
    startTime: '7:00 PM & 9:30 PM',
    timeSlot: 'Evening',
    price: '$30–$42',
    budgetTier: '$$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Comedy',
    description: 'Viral comic Geoffrey Asmus brings his crowd-work-heavy, profane stand-up to Dead Crow Comedy Room. A regular at NYC\'s Comedy Cellar and New Face of Comedy at Just for Laughs Montreal. Two shows nightly: 7 PM and 9:30 PM.',
    bookingUrl: 'https://deadcrowcomedy.com/',
    infoUrl: 'https://www.starnewsonline.com/story/entertainment/events/2026/02/25/events-happenings-things-to-do-whats-going-on-in-wilmington-nc-festivals-comedy-music-theater/88643157007/',
    tags: ['comedy', 'stand-up', 'crowd work', 'viral', 'nightlife'],
  },
  {
    id: 'cape-fear-hooley',
    name: '9th Annual Cape Fear Hooley Under the Bridge',
    address: 'Waterline Brewing, Wilmington',
    city: 'Wilmington',
    state: 'NC',
    lat: 34.2287,
    lng: -77.9498,
    distanceMiles: 120,
    driveTimeMinutes: 120,
    days: ['Saturday'],
    startTime: '11:30 AM',
    endTime: '6:00 PM',
    timeSlot: 'Morning',
    price: 'Free (donations accepted)',
    budgetTier: 'Free',
    weather: 'Outdoor – check forecast',
    weatherIcon: '🌧️',
    indoorOutdoor: 'Outdoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Festival',
    description: 'Annual Irish festival fundraiser for the Wilmington St. Patrick\'s Day Parade. Features Irish band Nine Times Around, Irish dance from Triggle Academy, Celtic tunes from the Banna Band, Wilmington Police Pipes and Drums, and food trucks. Free admission!',
    bookingUrl: 'https://www.capefearhooley.com/',
    infoUrl: 'https://wilmingtondowntown.com/events/annual-cape-fear-hooley-under-the-bridge/',
    tags: ['Irish', 'St. Patricks', 'free', 'outdoor', 'music', 'dance', 'beer', 'food trucks'],
  },
  {
    id: 'taste-of-ireland-wilmington',
    name: 'A Taste of Ireland – Kenan Auditorium UNCW',
    address: 'Kenan Auditorium, UNCW, 601 S College Rd',
    city: 'Wilmington',
    state: 'NC',
    lat: 34.2265,
    lng: -77.8765,
    distanceMiles: 120,
    driveTimeMinutes: 120,
    days: ['Saturday'],
    startTime: '7:30 PM',
    timeSlot: 'Evening',
    price: '$38–$68',
    budgetTier: '$$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Theater',
    description: '"The Irish Music and Dance Sensation" comes to UNCW\'s Kenan Auditorium. This world-touring show blends Celtic music, traditional Irish dance, and storytelling in a spectacular production that has entertained thousands globally.',
    bookingUrl: 'https://www.kenanauditorium.com/',
    infoUrl: 'https://www.starnewsonline.com/story/entertainment/events/2026/02/25/events-happenings-things-to-do-whats-going-on-in-wilmington-nc-festivals-comedy-music-theater/88643157007/',
    tags: ['Irish', 'dance', 'Celtic', 'theater', 'UNCW'],
  },
  {
    id: 'fourth-friday-wilmington',
    name: 'Fourth Friday Gallery Night – Downtown Wilmington',
    address: 'Downtown Wilmington (multiple venues)',
    city: 'Wilmington',
    state: 'NC',
    lat: 34.2354,
    lng: -77.9476,
    distanceMiles: 120,
    driveTimeMinutes: 120,
    days: ['Friday'],
    startTime: '6:00 PM',
    endTime: '9:00 PM',
    timeSlot: 'Evening',
    price: 'Free',
    budgetTier: 'Free',
    weather: 'Both (gallery crawl)',
    weatherIcon: '🌧️',
    indoorOutdoor: 'Both',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Arts & Culture',
    description: 'Monthly art gallery crawl through downtown Wilmington. February highlights: closing reception for "Art of the Object" at Cathryn O\'Donnell Gallery; opening of "Salt Sisters: Marsh to Mellow" at Burgwin-Wright House; closing of "Unique: A Rachard McIntyre Retrospective" at WHQR. Free!',
    infoUrl: 'https://artswilmington.org/',
    tags: ['art', 'gallery', 'free', 'downtown', 'crawl', 'opening reception'],
  },
  {
    id: 'sad-song-happy-hour',
    name: 'Sad Song Happy Hour – Bourgie Nights',
    address: 'Bourgie Nights, Wilmington',
    city: 'Wilmington',
    state: 'NC',
    lat: 34.2354,
    lng: -77.9476,
    distanceMiles: 120,
    driveTimeMinutes: 120,
    days: ['Sunday'],
    startTime: '7:00 PM',
    timeSlot: 'Evening',
    price: 'Free (donations)',
    budgetTier: 'Free',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Music',
    description: 'Monthly songwriter showcase in a listening-room environment. March edition features Paulonious (Paul Miller of Blue Karma), Max Agee (Lawn Enforcement), and Crowbar Jeremy. Two open mic drawings between sets. Doors 6 PM, show 7 PM. Free with donations.',
    infoUrl: 'https://www.starnewsonline.com/story/entertainment/events/2026/02/25/events-happenings-things-to-do-whats-going-on-in-wilmington-nc-festivals-comedy-music-theater/88643157007/',
    tags: ['singer-songwriter', 'acoustic', 'free', 'listening room', 'open mic'],
  },
  {
    id: 'moores-creek-battle',
    name: '250th Anniversary – Battle of Moores Creek Bridge',
    address: 'Moores Creek National Battlefield, 40 Patriots Hall Dr',
    city: 'Currie',
    state: 'NC',
    lat: 34.4587,
    lng: -78.1098,
    distanceMiles: 115,
    driveTimeMinutes: 115,
    days: ['Friday', 'Saturday'],
    startTime: 'Various (all day)',
    timeSlot: 'All Day',
    price: 'Free',
    budgetTier: 'Free',
    weather: 'Outdoor – check forecast',
    weatherIcon: '🌧️',
    indoorOutdoor: 'Outdoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'History',
    description: 'The 250th anniversary commemoration of the Feb. 27, 1776 Revolutionary War Battle of Moores Creek Bridge. Part of the America250 celebration and NC First in Freedom Festival. Education programs, battle commemorations, and live music. Free admission.',
    bookingUrl: 'https://www.ncfirstinfreedomfestival.com/',
    infoUrl: 'https://www.america250.nc.gov/first-freedom-festival',
    tags: ['Revolutionary War', 'history', 'free', 'America250', 'anniversary', 'battle'],
  },
  {
    id: 'wilmington-history-tour',
    name: 'Historic Happy Hour – Wilmington Drinks & History Tour',
    address: 'Gazebo Bar (starting point), Downtown Wilmington',
    city: 'Wilmington',
    state: 'NC',
    lat: 34.2354,
    lng: -77.9476,
    distanceMiles: 120,
    driveTimeMinutes: 120,
    days: ['Friday', 'Saturday', 'Sunday'],
    startTime: '4:00 PM',
    timeSlot: 'Afternoon',
    price: '$30',
    budgetTier: '$$',
    weather: 'Outdoor (walking tour)',
    weatherIcon: '🌧️',
    indoorOutdoor: 'Outdoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'History',
    description: 'Dive into Wilmington\'s vibrant history and architecture on a leisurely 1.5-mile walk, kicking off and wrapping up at cozy wine bars. Learn about the city\'s role in the American Revolution, Civil War, and more while enjoying drinks.',
    bookingUrl: 'https://www.eventbrite.com/d/nc--wilmington/wine-tasting-events/',
    infoUrl: 'https://www.wilmingtonandbeaches.com/',
    tags: ['history tour', 'walking tour', 'wine', 'downtown', 'America250'],
  },

  // ─── GREENSBORO (160 mi / 150 min) ───────────────────────────────────────────
  {
    id: 'gargoyles-fri',
    name: 'Greensboro Gargoyles Hockey – Pucks & Paws Night',
    address: 'First Horizon Coliseum, 1921 West Gate City Blvd',
    city: 'Greensboro',
    state: 'NC',
    lat: 36.0654,
    lng: -79.8321,
    distanceMiles: 160,
    driveTimeMinutes: 150,
    days: ['Friday'],
    startTime: '7:00 PM',
    timeSlot: 'Evening',
    price: '$15–$50+',
    budgetTier: '$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Sports',
    description: 'Greensboro Gargoyles vs. Norfolk Admirals on "Pucks and Paws Night" — bring your dog! Fun minor league hockey atmosphere with great value tickets. First Horizon Coliseum provides an intimate arena experience.',
    bookingUrl: 'https://gargoyleshockey.com/tickets',
    infoUrl: 'https://gargoyleshockey.com/',
    tags: ['hockey', 'minor league', 'pets welcome', 'family', 'sports'],
  },
  {
    id: 'gargoyles-sat',
    name: 'Greensboro Gargoyles Hockey vs. Norfolk Admirals',
    address: 'First Horizon Coliseum, 1921 West Gate City Blvd',
    city: 'Greensboro',
    state: 'NC',
    lat: 36.0654,
    lng: -79.8321,
    distanceMiles: 160,
    driveTimeMinutes: 150,
    days: ['Saturday'],
    startTime: '7:00 PM',
    timeSlot: 'Evening',
    price: '$15–$50+',
    budgetTier: '$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Sports',
    description: 'Greensboro Gargoyles vs. Norfolk Admirals at First Horizon Coliseum. Great minor league hockey action with affordable tickets. Lively crowd and fun arena atmosphere.',
    bookingUrl: 'https://gargoyleshockey.com/tickets',
    infoUrl: 'https://gargoyleshockey.com/',
    tags: ['hockey', 'minor league', 'sports', 'nightlife'],
  },
  {
    id: 'gargoyles-sun',
    name: 'Greensboro Gargoyles Hockey – Sunday Funday',
    address: 'First Horizon Coliseum, 1921 West Gate City Blvd',
    city: 'Greensboro',
    state: 'NC',
    lat: 36.0654,
    lng: -79.8321,
    distanceMiles: 160,
    driveTimeMinutes: 150,
    days: ['Sunday'],
    startTime: '3:00 PM',
    timeSlot: 'Afternoon',
    price: '$15–$50+',
    budgetTier: '$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Sports',
    description: '"Sunday Funday" game featuring the Greensboro Gargoyles vs. Atlanta. Family activities and giveaways. Early afternoon puck drop makes it easy to get home at a reasonable hour.',
    bookingUrl: 'https://gargoyleshockey.com/tickets',
    infoUrl: 'https://gargoyleshockey.com/',
    tags: ['hockey', 'minor league', 'family', 'Sunday Funday', 'giveaways'],
  },

  // ─── FAYETTEVILLE (100 mi / 100 min) ─────────────────────────────────────────
  {
    id: 'wine-design-fayetteville',
    name: 'Wine & Design – Open Studio Paint Night',
    address: '2180 Skibo Road Ste C',
    city: 'Fayetteville',
    state: 'NC',
    lat: 35.0654,
    lng: -78.9876,
    distanceMiles: 100,
    driveTimeMinutes: 100,
    days: ['Friday'],
    startTime: '6:30 PM',
    timeSlot: 'Evening',
    price: '$42',
    budgetTier: '$$$',
    weather: 'Indoor – any weather',
    weatherIcon: '🏠',
    indoorOutdoor: 'Indoor',
    veganOptions: null,
    vegetarianOptions: null,
    category: 'Classes',
    description: 'Open Studio paint night — you choose which painting to recreate! All materials provided, BYOB welcome. Artists walk all participants through the process. Great date night or group activity in Fayetteville.',
    bookingUrl: 'https://www.wineanddesign.com/calendar/fayetteville-nc',
    infoUrl: 'https://www.wineanddesign.com/calendar/fayetteville-nc',
    tags: ['painting', 'art class', 'BYOB', 'date night', 'creative'],
  },
];

// Helper functions
export function getEventsByDay(day: DayFilter): Event[] {
  return EVENTS.filter(e => e.days.includes(day));
}

export function getEventsByCategory(category: Category): Event[] {
  return EVENTS.filter(e => e.category === category);
}

export function getEventsByCity(city: string): Event[] {
  return EVENTS.filter(e => e.city.toLowerCase() === city.toLowerCase());
}

export const ALL_CITIES = Array.from(new Set(EVENTS.map(e => e.city))).sort();
export const ALL_CATEGORIES: Category[] = [
  'Music', 'Theater', 'Sports', 'Nature', 'Arts & Culture',
  'Food & Drink', 'History', 'Family', 'Brewery', 'Festival', 'Film', 'Comedy', 'Classes'
];

export const CATEGORY_ICONS: Record<Category, string> = {
  'Music': '🎵',
  'Theater': '🎭',
  'Sports': '🏆',
  'Nature': '🌲',
  'Arts & Culture': '🎨',
  'Food & Drink': '🍽️',
  'History': '🏛️',
  'Family': '👨‍👩‍👧‍👦',
  'Brewery': '🍺',
  'Festival': '🎪',
  'Film': '🎬',
  'Comedy': '😂',
  'Classes': '🎓',
};

export const CATEGORY_COLORS: Record<Category, string> = {
  'Music': 'bg-purple-100 text-purple-800 border-purple-200',
  'Theater': 'bg-orange-100 text-orange-800 border-orange-200',
  'Sports': 'bg-blue-100 text-blue-800 border-blue-200',
  'Nature': 'bg-green-100 text-green-800 border-green-200',
  'Arts & Culture': 'bg-pink-100 text-pink-800 border-pink-200',
  'Food & Drink': 'bg-yellow-100 text-yellow-800 border-yellow-200',
  'History': 'bg-amber-100 text-amber-800 border-amber-200',
  'Family': 'bg-cyan-100 text-cyan-800 border-cyan-200',
  'Brewery': 'bg-amber-100 text-amber-800 border-amber-200',
  'Festival': 'bg-teal-100 text-teal-800 border-teal-200',
  'Film': 'bg-indigo-100 text-indigo-800 border-indigo-200',
  'Comedy': 'bg-rose-100 text-rose-800 border-rose-200',
  'Classes': 'bg-violet-100 text-violet-800 border-violet-200',
};

export const CATEGORY_BORDER_COLORS: Record<Category, string> = {
  'Music': '#9333ea',
  'Theater': '#ea580c',
  'Sports': '#2563eb',
  'Nature': '#16a34a',
  'Arts & Culture': '#db2777',
  'Food & Drink': '#ca8a04',
  'History': '#d97706',
  'Family': '#0891b2',
  'Brewery': '#b45309',
  'Festival': '#0d9488',
  'Film': '#4f46e5',
  'Comedy': '#e11d48',
  'Classes': '#7c3aed',
};

export const BUDGET_COLORS: Record<BudgetTier, string> = {
  'Free': 'bg-emerald-100 text-emerald-800 border border-emerald-200',
  '$': 'bg-green-100 text-green-800 border border-green-200',
  '$$': 'bg-yellow-100 text-yellow-800 border border-yellow-200',
  '$$$': 'bg-orange-100 text-orange-800 border border-orange-200',
  '$$$$': 'bg-red-100 text-red-800 border border-red-200',
};
